events {
    worker_connections 1024;
}

http {
    upstream security {
        server security-service:9090;
    }
    
    upstream uploader {
        server uploader-service:9090;
    }
    
    upstream storage {
        server storage-service:9000;
    }
    
    server {
        listen 80;
        
        location /security/ {
            proxy_pass http://security/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        location /uploader/ {
            proxy_pass http://uploader/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        location /storage/ {
            proxy_pass http://storage/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        location /metrics {
            stub_status;
            access_log off;
        }
    }
}
